### ISSUE TITLE
JDBC_16 - Table 'xxx' does not exist or PDB is incorrect. Make sure the correct PDB was specified

### ISSUE THREAD

**Issue by littlebear-xbz** [streamsets/tutorials#93]
JDBC Producer
Insert to oracle error
use jar ojdbc8 or ojdbc6

JDBC_16 - Table 'xxx' does not exist or PDB is incorrect. Make sure the correct PDB was specified
![image](https://user-images.githubusercontent.com/13586820/45207222-086fb580-b2ba-11e8-9946-456c11a35ee4.png)
![image](https://user-images.githubusercontent.com/13586820/45207250-18879500-b2ba-11e8-900f-268c2aeff2c4.png)

**Comment by metadaddy** [comment]
Check the schema - are you sure it's `L_TEST`? Try leaving the schema blank - it should use the default schema for the user, or set it to the correct value. Closing this, since it doesn't seem to be an error in the tutorial. Please file an issue at https://issues.streamsets.com/ or ask a question at https://ask.streamsets.com/ if you can't get it working.
